name: Get Assignment
on:
  workflow_dispatch
    
jobs:
  check-contents:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    # Install dependencies
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    
    - name: Install checker 
      run: |
        pip install git+https://github.com/introcompsys/courseutils@main
    - name: check
      run: |
        rtitle="review-"$(date +"%Y-%m-%d")
        sysgetassignment --type review | gh issue create --title $rtitle --label review --body-file -
        pretitle="prepare-"$(date +"%Y-%m-%d")
        sysgetassignment | gh issue create --title $pretitle --label prepare --body-file -
        pratitle="practice-"$(date +"%Y-%m-%d")
        sysgetassignment --type practice| gh issue create --title $pratitle --label practice --body-file -
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
